version: '2'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=db
    command: postgres -c 'max_connections=1000'
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend-init:
      build: 
        context: ./docker-deploy/amazonWeb
        dockerfile: Dockerfile 
      command: /code/init_server.sh
      volumes:
        - ./docker-deploy/amazonWeb:/code
      depends_on:
        - db

  frontend:
      build: ./docker-deploy/amazonWeb
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./docker-deploy/amazonWeb:/code
      # ports:
      #   - "8000:8000"
      expose:
        - "8000"
      depends_on:
        - frontend-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - frontend


  backend:
    build: 
      context: ./docker-deploy/server
      dockerfile: Dockerfile
    command: bash -c "chmod o+x run.sh && ./run.sh"
    ports:
      - "5688:5688"
      - "8873:8873"
    depends_on:
      - db
      # - frontend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=db

volumes:
  db-data:
