# Generated by Django 4.1.5 on 2023-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_packages_user_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(default='created', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='status',
            field=models.CharField(default='idle', max_length=100, null=True),
        ),
    ]
