# Generated by Django 4.1.5 on 2023-04-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_packages_status_alter_trucks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='userx',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='usery',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truckx',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='trucky',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0, null=True)),
                ('packageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.packages')),
            ],
        ),
    ]
