# Generated by Django 4.1.5 on 2023-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_users_alter_packages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
